### ISSUE TITLE
Create List of Task Descriptions 

### ISSUE THREAD

**Issue by piebaker** [TyLanger/Tasks#2]
While the cryptic task descriptions are fun it would be nice to have a comprehensive list here on the github to refer back to for hints

**Comment by TyLanger** [comment]
I made a wiki that lists the tasks. It tells you a bit about how they work. I'll refer to it or link to it in the readme when I release the next update so it shows on the mod page.

**Comment by piebaker** [comment]
Awesome, thanks!
